[tool.poetry]
name = "ssss"
version = "0.0.0a0.post0.dev2"
description = ""
authors = ["Magnus Åberg <himself@magnusaberg.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
markdown = "^3.4.3"
staticjinja = "^4.1.3"

[tool.poetry.scripts]
ssss = "ssss.generate.site:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
